/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactsCard: typeof import('./src/components/ContactsCard.vue')['default']
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    EasyForm: typeof import('./src/components/EasyForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FormContainer: typeof import('./src/components/FormContainer.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
