/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactsCard: typeof import('./src/components/ContactsCard.vue')['default']
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    EasyForm: typeof import('./src/components/EasyForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormContainer: typeof import('./src/components/FormContainer.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FriendCard: typeof import('./src/components/FriendCard.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    RequestReceivedCard: typeof import('./src/components/RequestReceivedCard.vue')['default']
    RequestSentCard: typeof import('./src/components/RequestSentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
